<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-05-17T10:50:45Z" name="internet banking test app" finished-at="2021-05-17T10:51:16Z" duration-ms="31150">
    <groups>
    </groups>
    <test started-at="2021-05-17T10:50:45Z" name="internet Banking test" finished-at="2021-05-17T10:51:16Z" duration-ms="31150">
      <class name="com.intetbanking.testCases.TC_002_DDT_Login">
        <test-method is-config="true" signature="initialize(java.lang.String)[pri:0, instance:com.intetbanking.testCases.TC_002_DDT_Login@4a07d605]" started-at="2021-05-17T16:20:45Z" name="initialize" finished-at="2021-05-17T16:20:47Z" duration-ms="1854" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method signature="DDT_login(java.lang.String, java.lang.String)[pri:0, instance:com.intetbanking.testCases.TC_002_DDT_Login@4a07d605]" started-at="2021-05-17T16:20:48Z" name="DDT_login" data-provider="LoginData" finished-at="2021-05-17T16:20:58Z" duration-ms="10003" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr326123]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[qegagyg]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DDT_login -->
        <test-method signature="DDT_login(java.lang.String, java.lang.String)[pri:0, instance:com.intetbanking.testCases.TC_002_DDT_Login@4a07d605]" started-at="2021-05-17T16:20:58Z" name="DDT_login" data-provider="LoginData" finished-at="2021-05-17T16:21:03Z" duration-ms="5077" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr5555]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abcdefg]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.intetbanking.testCases.TC_002_DDT_Login.DDT_login(TC_002_DDT_Login.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DDT_login -->
        <test-method signature="DDT_login(java.lang.String, java.lang.String)[pri:0, instance:com.intetbanking.testCases.TC_002_DDT_Login@4a07d605]" started-at="2021-05-17T16:21:03Z" name="DDT_login" data-provider="LoginData" finished-at="2021-05-17T16:21:11Z" duration-ms="7845" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr326123]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[qegagyg]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DDT_login -->
        <test-method signature="DDT_login(java.lang.String, java.lang.String)[pri:0, instance:com.intetbanking.testCases.TC_002_DDT_Login@4a07d605]" started-at="2021-05-17T16:21:11Z" name="DDT_login" data-provider="LoginData" finished-at="2021-05-17T16:21:15Z" duration-ms="4403" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr4444]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hahahaha]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.intetbanking.testCases.TC_002_DDT_Login.DDT_login(TC_002_DDT_Login.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DDT_login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.intetbanking.testCases.TC_002_DDT_Login@4a07d605]" started-at="2021-05-17T16:21:15Z" name="tearDown" finished-at="2021-05-17T16:21:16Z" duration-ms="648" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.intetbanking.testCases.TC_002_DDT_Login -->
    </test> <!-- internet Banking test -->
  </suite> <!-- internet banking test app -->
</testng-results>
